//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by appleseedrenderer.rc
//
#define IDD_FORMVIEW_RENDERERPARAMS_ABOUT               100
#define IDC_TEXT_PLUGIN_VERSION                         101
#define IDC_TEXT_APPLESEED_VERSION                      102
#define IDC_STATIC_NEW_VERSION                          103
#define IDC_BUTTON_DOWNLOAD                             104
#define IDD_FORMVIEW_RENDERERPARAMS_IMAGESAMPLING       200
#define IDC_TEXT_PIXEL_SAMPLES                          201
#define IDC_SPINNER_PIXEL_SAMPLES                       202
#define IDC_TEXT_PASSES                                 203
#define IDC_SPINNER_PASSES                              204
#define IDC_TEXT_TILE_SIZE                              205
#define IDC_SPINNER_TILE_SIZE                           206
#define IDC_COMBO_FILTER                                207
#define IDC_TEXT_FILTER_SIZE                            208
#define IDC_SPINNER_FILTER_SIZE                         209
#define IDS_RENDERERPARAMS_FILTER_TYPE_1                210
#define IDS_RENDERERPARAMS_FILTER_TYPE_2                211
#define IDS_RENDERERPARAMS_FILTER_TYPE_3                212
#define IDS_RENDERERPARAMS_FILTER_TYPE_4                213
#define IDS_RENDERERPARAMS_FILTER_TYPE_5                214
#define IDS_RENDERERPARAMS_FILTER_TYPE_6                215
#define IDS_RENDERERPARAMS_FILTER_TYPE_7                216
#define IDS_RENDERERPARAMS_FILTER_TYPE_8                217
#define IDC_COMBO_SAMPLER_TYPE                          218
#define IDS_RENDERERPARAMS_SAMPLER_TYPE_1               219
#define IDS_RENDERERPARAMS_SAMPLER_TYPE_2               220
#define IDC_STATIC_ADAPTIVE_BATCH_SIZE                  221
#define IDC_TEXT_ADAPTIVE_BATCH_SIZE                    222
#define IDC_SPINNER_ADAPTIVE_BATCH_SIZE                 223
#define IDC_STATIC_MIN_ADAPTIVE_SAMPLES                 224
#define IDC_TEXT_MIN_ADAPTIVE_SAMPLES                   225
#define IDC_SPINNER_MIN_ADAPTIVE_SAMPLES                226
#define IDC_STATIC_MAX_ADAPTIVE_SAMPLES                 227
#define IDC_TEXT_MAX_ADAPTIVE_SAMPLES                   228
#define IDC_SPINNER_MAX_ADAPTIVE_SAMPLES                229
#define IDC_STATIC_ADAPTIVE_NOISE_THRESHOLD             230
#define IDC_TEXT_ADAPTIVE_NOISE_THRESHOLD               231
#define IDC_SPINNER_ADAPTIVE_NOISE_THRESHOLD            232
#define IDC_TEXT_NOISE_SEED                             233
#define IDC_SPINNER_NOISE_SEED                          234
#define IDC_CHECK_ENABLE_NOISE_SEED                     235
#define IDD_FORMVIEW_RENDERERPARAMS_PATH_TRACING        300
#define IDC_CHECK_GI                                    301
#define IDC_CHECK_CAUSTICS                              302
#define IDC_STATIC_BOUNCES                              303
#define IDC_TEXT_BOUNCES                                304
#define IDC_SPINNER_BOUNCES                             305
#define IDC_CHECK_MAX_RAY_INTENSITY                     306
#define IDC_TEXT_MAX_RAY_INTENSITY                      307
#define IDC_SPINNER_MAX_RAY_INTENSITY                   308
#define IDC_CHECK_BACKGROUND_EMITS_LIGHT                309
#define IDC_STATIC_BACKGROUND_ALPHA                     310
#define IDC_TEXT_BACKGROUND_ALPHA                       311
#define IDC_SPINNER_BACKGROUND_ALPHA                    312
#define IDC_CHECK_FORCE_OFF_DEFAULT_LIGHT               313
#define IDC_CHECK_ROUGHNESS                             314
#define IDC_CHECK_ENABLE_DBOUNCE                        315
#define IDC_TEXT_DBOUNCES                               316
#define IDC_SPINNER_DBOUNCES                            317
#define IDC_CHECK_ENABLE_GBOUNCE                        318
#define IDC_TEXT_GBOUNCES                               319
#define IDC_SPINNER_GBOUNCES                            320
#define IDC_CHECK_ENABLE_SBOUNCE                        321
#define IDC_TEXT_SBOUNCES                               322
#define IDC_SPINNER_SBOUNCES                            323
#define IDC_CHECK_ENABLE_VBOUNCE                        324
#define IDC_TEXT_VBOUNCES                               325
#define IDC_SPINNER_VBOUNCES                            326
#define IDC_STATIC_DL_SAMPLES                           327
#define IDC_TEXT_DL_SAMPLES                             328
#define IDC_SPINNER_DL_SAMPLES                          329
#define IDC_STATIC_DL_LOW_LIGHT_THRESHOLD               330
#define IDC_TEXT_DL_LOW_LIGHT_THRESHOLD                 331
#define IDC_SPINNER_DL_LOW_LIGHT_THRESHOLD              332
#define IDC_STATIC_ENV_SAMPLES                          333
#define IDC_TEXT_ENV_SAMPLES                            334
#define IDC_SPINNER_ENV_SAMPLES                         335
#define IDC_STATIC_RR_MIN_PATH_LENGTH                   336
#define IDC_TEXT_RR_MIN_PATH_LENGTH                     337
#define IDC_SPINNER_RR_MIN_PATH_LENGTH                  338
#define IDC_CHECK_DL                                    339
#define IDC_STATIC_VOL_DISTANCE_SAMPLES                 340
#define IDC_TEXT_VOL_DISTANCE_SAMPLES                   341
#define IDC_SPINNER_VOL_DISTANCE_SAMPLES                342
#define IDC_CHECK_LIGHT_OUTSIDE_VOLUMES                 343
#define IDD_FORMVIEW_RENDERERPARAMS_OUTPUT              400
#define IDC_RADIO_RENDER                                401
#define IDC_RADIO_SAVEPROJECT                           402
#define IDC_RADIO_SAVEPROJECT_AND_RENDER                403
#define IDC_STATIC_PROJECT_FILEPATH                     404
#define IDC_TEXT_PROJECT_FILEPATH                       405
#define IDC_BUTTON_BROWSE                               406
#define IDC_STATIC_SCALE_MULTIPLIER                     407
#define IDC_TEXT_SCALE_MULTIPLIER                       408
#define IDC_SPINNER_SCALE_MULTIPLIER                    409
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_1            410
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_2            411
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_3            412
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_4            413
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_5            414
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_6            415
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_7            416
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_8            417
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_9            418
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_10           419
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_11           420
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_12           421
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_13           422
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_14           423
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_15           424
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_16           425
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_17           426
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_18           427
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_19           428
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_20           429
#define IDC_COMBO_DIAGNOSTIC_SHADER_MODE                430
#define IDC_TEXT_DIAGNOSTIC_SHADER_MODE                 431
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_21           440
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_22           441
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_23           442
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_24           443
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_25           444
#define IDS_RENDERERPARAMS_SHADER_OVERRIDE_26           445
#define IDC_TEXT_MATERIAL_PREVIEW_QUALITY               450
#define IDC_SPINNER_MATERIAL_PREVIEW_QUALITY            451
#define IDC_STATIC_MATERIAL_PREVIEW_QUALITY             452
#define IDD_FORMVIEW_RENDERERPARAMS_SYSTEM              500
#define IDC_TEXT_RENDERINGTHREADS                       501
#define IDC_SPINNER_RENDERINGTHREADS                    502
#define IDC_CHECK_LOW_PRIORITY_MODE                     503
#define IDC_CHECK_USE_MAX_PROCEDURAL_MAPS               504
#define IDC_CHECK_LOG_MATERIAL_EDITOR                   505
#define IDC_TEXT_TEXTURE_CACHE_SIZE                     506
#define IDC_SPINNER_TEXTURE_CACHE_SIZE                  507
#define IDC_CHECK_ENABLE_EMBREE                         508
#define IDD_DIALOG_LOG                                  600
#define IDC_COMBO_LOG                                   601
#define IDC_STATIC_LOG                                  602
#define IDC_BUTTON_LOG                                  603
#define IDC_EDIT_LOG                                    604
#define IDC_CHECK_RENDER_STAMP                          605
#define IDC_TEXT_RENDER_STAMP                           606
#define IDS_RENDERERPARAMS_LOG_OPEN_MODE_1              607
#define IDS_RENDERERPARAMS_LOG_OPEN_MODE_2              608
#define IDS_RENDERERPARAMS_LOG_OPEN_MODE_3              609
#define IDS_RENDERERPARAMS_LOG_OPEN_MODE_4              610
#define IDD_FORMVIEW_RENDERERPARAMS_POSTPROCESSING      700
#define IDC_COMBO_DENOISE_MODE                          701
#define IDC_CHECK_SKIP_DENOISED_PIXELS                  702
#define IDC_CHECK_RANDOM_PIXEL_ORDER                    703
#define IDC_CHECK_PREFILTER_SPIKES                      704
#define IDC_STATIC_SPIKE_THRESHOLD                      705
#define IDC_TEXT_SPIKE_THRESHOLD                        706
#define IDC_SPINNER_SPIKE_THRESHOLD                     707
#define IDC_STATIC_PATCH_DISTANCE                       708
#define IDC_TEXT_PATCH_DISTANCE                         709
#define IDC_SPINNER_PATCH_DISTANCE                      710
#define IDC_STATIC_DENOISE_SCALES                       711
#define IDC_TEXT_DENOISE_SCALES                         712
#define IDC_SPINNER_DENOISE_SCALES                      713
#define IDS_RENDERERPARAMS_DENOISE_MODE_1               714
#define IDS_RENDERERPARAMS_DENOISE_MODE_2               715
#define IDS_RENDERERPARAMS_DENOISE_MODE_3               716
#define IDD_FORMVIEW_RENDERERPARAMS_LIGHTING            800
#define IDS_RENDERERPARAMS_LIGHTING_ALGORITHM_1         801
#define IDS_RENDERERPARAMS_LIGHTING_ALGORITHM_2         802
#define IDS_RENDERERPARAMS_LIGHTING_ALGORITHM_3         803
#define IDC_COMBO_LIGHTING_ALGORITHM                    804
#define IDC_COMBO_LIGHT_SAMPLING_ALGORITHM              805
#define IDS_RENDERERPARAMS_LIGHT_SAMPLER_TYPE_1         806
#define IDC_CHECK_ENABLE_IMPORTANCE_SAMPLING            810
#define IDD_FORMVIEW_RENDERERPARAMS_SPPM                900
#define IDC_COMBO_SPPM_PHOTON_TYPE                      901
#define IDS_RENDERERPARAMS_SPPM_PHOTON_TYPE_1           902
#define IDS_RENDERERPARAMS_SPPM_PHOTON_TYPE_2           903
#define IDC_COMBO_SPPM_DL_TYPE                          904
#define IDS_RENDERERPARAMS_SPPM_DL_TYPE_1               905
#define IDS_RENDERERPARAMS_SPPM_DL_TYPE_2               906
#define IDS_RENDERERPARAMS_SPPM_DL_TYPE_3               907
#define IDC_CHECK_SPPM_CAUSTICS                         908
#define IDC_CHECK_SPPM_IMAGE_BASED_LIGHTING             909
#define IDC_STATIC_SPPM_PT_BOUNCES                      910
#define IDC_TEXT_SPPM_PT_BOUNCES                        911
#define IDC_SPINNER_SPPM_PT_BOUNCES                     912
#define IDC_CHECK_SPPM_PT_BOUNCES                       913
#define IDC_STATIC_SPPM_PT_RR_MIN_PATH_LENGTH           914
#define IDC_TEXT_SPPM_PT_RR_MIN_PATH_LENGTH             915
#define IDC_SPINNER_SPPM_PT_RR_MIN_PATH_LENGTH          916
#define IDC_STATIC_SPPM_PT_LIGHT_PHOTONS                917
#define IDC_TEXT_SPPM_PT_LIGHT_PHOTONS                  918
#define IDC_SPINNER_SPPM_PT_LIGHT_PHOTONS               919
#define IDC_STATIC_SPPM_PT_ENVIRONMENT_PHOTONS          920
#define IDC_TEXT_SPPM_PT_ENVIRONMENT_PHOTONS            921
#define IDC_SPINNER_SPPM_PT_ENVIRONMENT_PHOTONS         922
#define IDC_STATIC_SPPM_RADIANCE_BOUNCES                923
#define IDC_TEXT_SPPM_RADIANCE_BOUNCES                  924
#define IDC_SPINNER_SPPM_RADIANCE_BOUNCES               925
#define IDC_CHECK_SPPM_RADIANCE_BOUNCES                 926
#define IDC_STATIC_SPPM_RADIANCE_RR_MIN_PATH_LENGTH     927
#define IDC_TEXT_SPPM_RADIANCE_RR_MIN_PATH_LENGTH       928
#define IDC_SPINNER_SPPM_RADIANCE_RR_MIN_PATH_LENGTH    929
#define IDC_STATIC_SPPM_RADIANCE_INITIAL_RADIUS         930
#define IDC_TEXT_SPPM_RADIANCE_INITIAL_RADIUS           931
#define IDC_SPINNER_SPPM_RADIANCE_INITIAL_RADIUS        932
#define IDC_STATIC_SPPM_RADIANCE_MAX_PHOTONS            933
#define IDC_TEXT_SPPM_RADIANCE_MAX_PHOTONS              934
#define IDC_SPINNER_SPPM_RADIANCE_MAX_PHOTONS           935
#define IDC_STATIC_SPPM_RADIANCE_ALPHA                  936
#define IDC_TEXT_SPPM_RADIANCE_ALPHA                    937
#define IDC_SPINNER_SPPM_RADIANCE_ALPHA                 938
#define IDC_CHECK_SPPM_VIEW_PHOTONS                     939
#define IDC_SPINNER_SPPM_VIEW_PHOTONS_RADIUS            940
#define IDC_TEXT_SPPM_VIEW_PHOTONS_RADIUS               941
#define IDC_STATIC_SPPM_VIEW_PHOTONS_RADIUS             942
#define IDC_CHECK_SPPM_MAX_RAY_INTENSITY                943
#define IDC_SPINNER_SPPM_MAX_RAY_INTENSITY              944
#define IDC_TEXT_SPPM_MAX_RAY_INTENSITY                 945
#define IDC_STATIC_SPPM_MAX_RAY_INTENSITY               946

#define IDC_STATIC_LIGHTING                             453
#define IDC_STATIC_OVERRIDE_MATERIAL                    454
#define IDC_BUTTON_OVERRIDE_MATERIAL                    455
#define IDC_CHECK_OVERRIDE_MATERIAL                     456
#define IDC_CHECK_OVERRIDE_MATERIAL_SKIP_LIGHTS         457
#define IDC_CHECK_OVERRIDE_MATERIAL_SKIP_GLASS          458

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
