//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by appleseedrenderer.rc
//
#define IDD_FORMVIEW_RENDERERPARAMS_SAMPLING 101
#define IDD_FORMVIEW_RENDERERPARAMS_SYSTEM 104
#define IDD_FORMVIEW_RENDERERPARAMS_OUTPUT 105
#define IDD_FORMVIEW_RENDERERPARAMS_IMAGESAMPLING 106
#define IDD_FORMVIEW_RENDERERPARAMS_LIGHTING 107
#define IDD_FORMVIEW_RENDERERPARAMS_ABOUT 108
#define IDC_SPINNER_PIXELSAMPLES        1003
#define IDC_TEXT_PIXELSAMPLES           1004
#define IDC_TEXT_PASSES                 1005
#define IDC_SPINNER_PASSES              1006
#define IDC_TEXT_RENDERINGTHREADS       1008
#define IDC_SPINNER_RENDERINGTHREADS    1009
#define IDC_RADIO_RENDER                1010
#define IDC_RADIO_SAVEPROJECT           1011
#define IDC_RADIO_SAVEPROJECT_AND_RENDER 1012
#define IDC_BUTTON_BROWSE               1013
#define IDC_TEXT_PROJECT_FILEPATH       1014
#define IDC_TEXT_BOUNCES                1015
#define IDC_SPINNER_BOUNCES             1016
#define IDC_TEXT_APPLESEED_VERSION      1016
#define IDC_CHECK_GI                    1017
#define IDC_CHECK_BACKGROUND_EMITS_LIGHT 1018
#define IDC_TEXT_PLUGIN_VERSION         1020
#define IDC_BUTTON_DOWNLOAD             1022
#define IDC_STATIC_NEW_VERSION          1023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
